name: Run Tests

on:
  push:
    branch:
      - "*"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: >-
          python -m
          pip install
          pytest pytest-cov coverage numpy
      - name: Test with pytest
        run: |
          pytest -v --color=yes
